spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: health-processing-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: monitoring_event_contract.event
        spring.json.value.default.type: monitoring_event_contract.event.HealthEvent
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

health:
  alert-topic: health-alerts

monitoring:
  heartbeat:
    expiry-threshold-ms: 30000   # 30 seconds
    check-interval-ms: 10000     # run expiry engine every 10 seconds